### ISSUE TITLE
Non-urgent questions re: main.css

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/ecommerce-pattern-library#2]
Just curious why we need to include the empty front matter in this file for styling (ex. buttons) to render? 

@thomasjbradley

**Comment by thomasjbradley** [comment]
Without the frontmatter Jekyll will just ignore the file and not parse or render it.

**Comment by MacKenzieRose** [comment]
How is it able to still render the general pattern library stylings without the empty frontmatter (ex. typografier/fonts/colours)? Or is it not Jekyll that renders those?

**Comment by thomasjbradley** [comment]
It’s kind of a combination of Jekyll & Patternbot. Patterbot looks specifically for the `theme.css` file in order to find the colours & typefaces and such.

But then Patternbot also looks for `main.css` when it’s rendering individual patterns and adds that to the `<head>` tag automatically for each pattern. But, `main.css` needs to be rendered by Jekyll so that it concatenates all the different CSS files.

**Comment by MacKenzieRose** [comment]
Makes sense! Thanks @thomasjbradley :)

**Comment by MacKenzieRose** [comment]
@missmadore
